build: add bom module
micronaut-projects/micronaut-mqtt pull request #128
Opened 2022-03-02 06:35 UTC by sdelamo

[ci skip]

2022-03-02 12:41 UTC, timyates requested changes

2022-03-02 12:41 UTC, timyates commented on mqtt-bom/build.gradle
> +        api("org.eclipse.paho:org.eclipse.paho.client.mqttv3:$pahov3Version")
This is an `implementation` class in the `mqttv3` project, not an `api` one 🤔

2022-03-03 03:44 UTC, sdelamo commented on mqtt-bom/build.gradle
> +        api("org.eclipse.paho:org.eclipse.paho.client.mqttv3:$pahov3Version")
do you think we should not expose it in the BOM? or do you think we should change it to be `api` in `mqttv3`. I think the latter probably makes more sense.

2022-03-03 13:37 UTC, timyates commented on mqtt-bom/build.gradle
> +        api("org.eclipse.paho:org.eclipse.paho.client.mqttv3:$pahov3Version")
I agree it should probably be the latter

2022-03-04 01:24 UTC, sdelamo commented on mqtt-bom/build.gradle
> +        api("org.eclipse.paho:org.eclipse.paho.client.mqttv3:$pahov3Version")
Resolved via https://github.com/micronaut-projects/micronaut-mqtt/pull/128/commits/eaae750a75b094339d8508954ea752543ec67e61

2022-03-04 01:49 UTC, merged