#144 integrate with HIveMQ client feature complete
micronaut-projects/micronaut-mqtt pull request #298
Opened 2023-06-21 13:13 UTC by skobow

2023-06-30 13:07 UTC, timyates requested changes
Really really nice! 😎 👍 

Couple of requests

2023-06-30 13:07 UTC, timyates commented on mqtt-hivemq/src/main/java/io/micronaut/mqtt/hivemq/v3/client/Mqtt3ClientAdapter.java
> +/*
Do you have Graal configuration for the hivemq client?

I copied `test-suite-mqttv3-graal` to `test-suite-hivemq-mqttv3-graal`, added

`
@Property(name = "mqtt.client.mqtt-version", value = "3")
`

To the `MqttTest` 

and changed `test-suite-hivemq-mqttv3-graal/build.gradle.kts` so its dependencies were

```
dependencies {
    testImplementation(projects.micronautMqttHivemq)
}
```

Running `./gradlew :test-suite-hivemq-mqttv3-graal:test` worked 😎 👍 

But switching to use Graal 17 and running `./gradlew :test-suite-hivemq-mqttv3-graal:nativeTest` failed with a Graal reflection error:

https://ge.micronaut.io/s/yf7uam4fmseg6/console-log?task=:test-suite-hivemq-mqttv3-graal:nativeTest

2023-06-30 13:07 UTC, timyates commented on mqtt-hivemq/src/main/java/io/micronaut/mqtt/hivemq/v3/client/Mqtt3ClientAdapter.java
> +                // TODO: populate MqttMessage properly
Does this need addressing?

2023-06-30 13:07 UTC, timyates commented on mqtt-hivemq/src/main/java/io/micronaut/mqtt/hivemq/v5/client/Mqtt5ClientAdapter.java
> +                // TODO: populate MqttMessage properly
Does this need addressing?

2023-06-30 14:13 UTC, timyates commented on mqtt-hivemq/src/main/java/io/micronaut/mqtt/hivemq/v3/client/Mqtt3ClientAdapter.java
> +/*
Oooooh, so I found this PR from last week:

https://github.com/hivemq/hivemq-mqtt-client/pull/578

If I add

```diff
diff --git a/mqtt-hivemq/src/main/resources/META-INF/native-image/io.micronaut.mqtt/mqtt-hivemq/reflect-config.json b/mqtt-hivemq/src/main/resources/META-INF/native-image/io.micronaut.mqtt/mqtt-hivemq/reflect-config.json
index e69de29..c82657e 100644
--- a/mqtt-hivemq/src/main/resources/META-INF/native-image/io.micronaut.mqtt/mqtt-hivemq/reflect-config.json
+++ b/mqtt-hivemq/src/main/resources/META-INF/native-image/io.micronaut.mqtt/mqtt-hivemq/reflect-config.json
@@ -0,0 +1,18 @@
+[
+  {
+    "name": "org.jctools.queues.BaseSpscLinkedArrayQueueConsumerField",
+    "fields": [
+      {
+        "name": "consumerIndex"
+      }
+    ]
+  },
+  {
+    "name": "org.jctools.queues.BaseSpscLinkedArrayQueueProducerFields",
+    "fields": [
+      {
+        "name": "producerIndex"
+      }
+    ]
+  }
+]
```

Then the Graal native tests pass

2023-06-30 17:35 UTC, skobow commented on mqtt-hivemq/src/main/java/io/micronaut/mqtt/hivemq/v3/client/Mqtt3ClientAdapter.java
> +@Requires(property = "mqtt.client.mqtt-version", value = "3")
Done. I additionally set MQTT v5 to be the default even if the property is not provided.

2023-07-01 14:41 UTC, skobow commented on mqtt-hivemq/src/main/java/io/micronaut/mqtt/hivemq/v5/client/Mqtt5ClientAdapter.java
> +                // TODO: populate MqttMessage properly
Added population of missing properties. Done.

2023-07-07 06:05 UTC, sdelamo commented
@skobow are ok you of us merging this PR into the base branch and review adjusting the other PR?

2023-07-07 08:42 UTC, skobow commented
> 

@sdelamo you mean PR #256? I am absolutely fine with merging?

2023-07-07 08:48 UTC, skobow commented
> 

@timyates anything I can assist with? My goal was that v3 and v5 could possibly use the same configuration. Of course there are some differences but non should be conflicting. But maybe I just didn't get the issue right.

2023-07-07 09:59 UTC, timyates commented
@skobow No, we should be fine...  Our annotation processor that generates docs didn't expect multiple configurations in the same module with the same prefix...  We can take it from here :-)

2023-07-07 09:59 UTC, merged