HealthIndicator support.
micronaut-projects/micronaut-mqtt pull request #56
Opened 2021-02-22 16:17 UTC by ckapop

2021-02-22 16:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-mqtt?pullRequest=56) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-mqtt?pullRequest=56) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-mqtt?pullRequest=56) it.</sub>

2021-02-22 22:50 UTC, ckapop commented
GraalVM CE CI build is having an issue with the docs-examples. Not sure if it is a known problem or not.

2021-02-23 08:17 UTC, graemerocher commented on mqttv3/build.gradle
> +    implementation "io.micronaut:micronaut-management:$micronautVersion"
This should be `compileOnly`

2021-02-23 08:17 UTC, graemerocher commented on mqttv5/build.gradle
> +    implementation "io.micronaut:micronaut-management:$micronautVersion"
This should be `compileOnly`

2021-02-23 08:17 UTC, graemerocher commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> + * A {@link HealthIndicator} for Mqtt Client.
Please add `@author` and `@since` tags

2021-02-23 08:18 UTC, graemerocher commented on mqttv3/src/main/java/io/micronaut/mqtt/v3/client/health/MqttHealthIndicator.java
> +@Requires(property = HealthEndpoint.PREFIX + ".mqtt.client.enabled", value = "true")
Use `StringUtils.TRUE`

2021-02-23 08:18 UTC, graemerocher commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> +@Requires(property = HealthEndpoint.PREFIX + ".mqtt.client.enabled", value = "true")
Use `StringUtils.TRUE`

2021-02-23 16:03 UTC, ckapop commented on mqttv3/build.gradle
> +    implementation "io.micronaut:micronaut-management:$micronautVersion"
Doing this caused the build to fail.

2021-02-23 16:04 UTC, ckapop commented on mqttv5/build.gradle
> +    implementation "io.micronaut:micronaut-management:$micronautVersion"
Doing this causes the build to fail.

2021-02-23 16:07 UTC, ckapop commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> + * A {@link HealthIndicator} for Mqtt Client.
Done.

2021-02-23 16:18 UTC, ckapop commented on mqttv3/src/main/java/io/micronaut/mqtt/v3/client/health/MqttHealthIndicator.java
> +@Requires(property = HealthEndpoint.PREFIX + ".mqtt.client.enabled", value = "true")
Done.

2021-02-23 16:18 UTC, ckapop commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> +@Requires(property = HealthEndpoint.PREFIX + ".mqtt.client.enabled", value = "true")
Done.

2021-02-23 20:15 UTC, ckapop commented on mqttv5/build.gradle
> +    implementation "io.micronaut:micronaut-management:$micronautVersion"
However, adding this in addition to `compileOnly` seemed to work. I noticed this is how [https://github.com/micronaut-projects/micronaut-sql/blob/master/vertx-pg-client/build.gradle](url) did it.

`testImplementation "io.micronaut:micronaut-management:$micronautVersion"`

2021-02-23 20:15 UTC, ckapop commented on mqttv3/build.gradle
> +    implementation "io.micronaut:micronaut-management:$micronautVersion"
However, adding this in addition to `compileOnly` seemed to work. I noticed this is how [https://github.com/micronaut-projects/micronaut-sql/blob/master/vertx-pg-client/build.gradle](url) did it.

`testImplementation "io.micronaut:micronaut-management:$micronautVersion"`

2021-02-23 20:16 UTC, ckapop commented on mqttv3/build.gradle
> +    implementation "io.micronaut:micronaut-management:$micronautVersion"
However, adding this in addition to `compileOnly` seemed to work. I noticed this is how [https://github.com/micronaut-projects/micronaut-sql/blob/master/vertx-pg-client/build.gradle](url) did it.

`testImplementation "io.micronaut:micronaut-management:$micronautVersion"`

2021-02-23 20:16 UTC, ckapop commented on mqttv5/build.gradle
> +    implementation "io.micronaut:micronaut-management:$micronautVersion"
However, adding this in addition to `compileOnly` seemed to work. I noticed this is how [https://github.com/micronaut-projects/micronaut-sql/blob/master/vertx-pg-client/build.gradle](url) did it.

`testImplementation "io.micronaut:micronaut-management:$micronautVersion"`

2021-03-05 03:17 UTC, ckapop commented
Anything else I need to do?

2021-03-07 09:00 UTC, graemerocher commented
@jameskleeh can you do a final review?

2021-03-08 05:20 UTC, jameskleeh commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> +        HealthResult.Builder builder = HealthResult.builder(NAME, status).details(Collections.singletonMap("class", client.getClass().getName()));
Perhaps add a message here to say the client reported its not connected?

2021-03-08 05:22 UTC, jameskleeh commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> +@Requires(property = HealthEndpoint.PREFIX + ".mqtt.client.enabled", value = StringUtils.TRUE)
In general the `client` portion of this config is redundant. You wouldn't have a health indicator for the server side of the connection. I think this can be condensed to `endpoints.health.mqtt.enabled`

2021-03-08 05:22 UTC, jameskleeh commented
Needs documentation

2021-03-08 05:22 UTC, jameskleeh requested changes
Needs documentation

2021-03-13 13:25 UTC, ckapop commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> +@Requires(property = HealthEndpoint.PREFIX + ".mqtt.client.enabled", value = StringUtils.TRUE)
I used the vertx-pg-client as a guide and they include `client` in the configuration so I wanted to be consistent with other plugins.
If having different configuration paths wont be confusing let me know and I will change it.

https://micronaut-projects.github.io/micronaut-sql/latest/guide/#vertxpgclient
https://github.com/micronaut-projects/micronaut-sql/blob/master/vertx-pg-client/src/main/java/io/micronaut/configuration/vertx/pg/client/health/PgHealthIndicator.java

`@Requires(property = HealthEndpoint.PREFIX + ".vertx.pg.client.enabled", notEquals = StringUtils.FALSE)`

2021-03-13 13:26 UTC, ckapop commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> +        HealthResult.Builder builder = HealthResult.builder(NAME, status).details(Collections.singletonMap("class", client.getClass().getName()));
When you say message do you mean code comment, log message, console output of some kind?

2021-03-13 13:28 UTC, ckapop commented
> Needs documentation

I agree, but I didn't know where this would go. If you could point me to the correct location for the documentation I will update it.

2021-06-16 14:04 UTC, ckapop commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> +@Requires(property = HealthEndpoint.PREFIX + ".mqtt.client.enabled", value = StringUtils.TRUE)
@jameskleeh : So did my comment make sense at all?

2021-06-16 14:16 UTC, jameskleeh commented on mqttv5/src/main/java/io/micronaut/mqtt/v5/client/health/MqttHealthIndicator.java
> +        HealthResult.Builder builder = HealthResult.builder(NAME, status).details(Collections.singletonMap("class", client.getClass().getName()));
I meant as a detail in the health result

2021-06-16 14:19 UTC, jameskleeh commented
> > Needs documentation
> 
> I agree, but I didn't know where this would go. If you could point me to the correct location for the documentation I will update it.

Our documentation is here https://github.com/micronaut-projects/micronaut-mqtt/tree/master/src/main/docs/guide

It's just a matter of adding a top level section to the docs and explaining that a health indicator exists and how to configure it. Use the existing documentation as a guide

2021-06-16 14:20 UTC, jameskleeh commented
Thanks for following back up on this - I appreciate it

2021-06-22 11:27 UTC, ilopmar commented
@jameskleeh @graemerocher is this ready for merge from your point of view?

2021-06-22 12:14 UTC, jameskleeh commented
Yep

On Tue, Jun 22, 2021 at 7:28 AM Iván López ***@***.***> wrote:

> @jameskleeh <https://github.com/jameskleeh> @graemerocher
> <https://github.com/graemerocher> is this ready for merge from your point
> of view?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/micronaut-projects/micronaut-mqtt/pull/56#issuecomment-865902633>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMCVLLG3I5OY5M6YFYJXWDTUBXUFANCNFSM4YAZYBWQ>
> .
>

2021-07-22 03:17 UTC, jameskleeh commented
Closing in favor of https://github.com/micronaut-projects/micronaut-mqtt/pull/87

2021-07-22 03:17 UTC, closed without merging